"""Builds ZygorTalentAdvisorCOA\\Data.lua from Ascension Sidekick's CoA leveling builds.

Inputs (in this folder):
  data.js     https://ascensionsidekick.com/data.js  (refresh with: curl -sSL -o data.js https://ascensionsidekick.com/data.js)
  nodes.tsv   CoA tree nodes (ID, name, class, tab, spells) dumped from the CoA patch's CoATalentNodeData.lua by dump_nodes.lua
  aliases.tsv spec tab aliases (class file, internal tab name, display name) dumped by dump_aliases.lua

  python build_ztacoa_data.py <output Data.lua>
"""
import json, sys, time

OUT = sys.argv[1]

t = open('data.js', encoding='utf-8').read()
D = json.loads(t[t.index('=') + 1:].strip().rstrip(';'))
LB = D['coaLevelBuilds']

nodes = {}
for line in open('nodes.tsv', encoding='latin-1'):
    i, n, c, tab, sp, typ = line.rstrip('\n').split('\t')
    nodes.setdefault(int(i), {'spells': [int(x) for x in sp.split(',') if x], 'classFile': c})

aliases = {}
for line in open('aliases.tsv', encoding='utf-8'):
    cls, frm, to = line.rstrip('\n').split('\t')
    aliases.setdefault(cls, {})[frm] = to

# Site class name -> in-game class token (2nd return of UnitClass) and CoA class file name.
CLASSES = {
    'Barbarian': ('BARBARIAN', 'Barbarian'), 'Witch Doctor': ('WITCHDOCTOR', 'WitchDoctor'),
    'Felsworn': ('DEMONHUNTER', 'DemonHunter'), 'Witch Hunter': ('WITCHHUNTER', 'WitchHunter'),
    'Stormbringer': ('STORMBRINGER', 'Stormbringer'), 'Knight of Xoroth': ('FLESHWARDEN', 'KnightOfXoroth'),
    'Guardian': ('GUARDIAN', 'Guardian'), 'Templar': ('MONK', 'Monk'), 'Bloodmage': ('SONOFARUGAL', 'SonOfArugal'),
    'Ranger': ('RANGER', 'Ranger'), 'Chronomancer': ('CHRONOMANCER', 'Chronomancer'),
    'Necromancer': ('NECROMANCER', 'Necromancer'), 'Pyromancer': ('PYROMANCER', 'Pyromancer'),
    'Cultist': ('CULTIST', 'Cultist'), 'Starcaller': ('STARCALLER', 'Starcaller'), 'Sun Cleric': ('SUNCLERIC', 'SunCleric'),
    'Tinker': ('TINKER', 'Tinker'), 'Venomancer': ('PROPHET', 'Venomancer'), 'Reaper': ('REAPER', 'Reaper'),
    'Primalist': ('WILDWALKER', 'Primalist'), 'Runemaster': ('SPIRITMAGE', 'Runemaster'),
}
missing = set(LB) - set(CLASSES)
assert not missing, 'unmapped site classes: %s' % missing


def lua_str(s):
    s = (s or '').replace('\\', '\\\\').replace('"', '\\"').replace('\r', '').replace('\n', ' ')
    return '"' + s + '"'


def pick_lua(p, rank):
    nd = nodes[p['id']]
    parts = ['n=%s' % lua_str(p['n']), 'node=%d' % p['id'], 'kind="%s"' % (p.get('kind') or 'T'),
             'spells={%s}' % ','.join(str(s) for s in nd['spells'])]
    if rank > 1: parts.append('rank=%d' % rank)
    for k in ('lvl', 'rl', 'ae', 'te'):
        if p.get(k): parts.append('%s=%d' % (k, p[k]))
    if p.get('auto'): parts.append('auto=true')
    if p.get('why'): parts.append('why=%s' % lua_str(p['why'][:240]))
    return '{' + ', '.join(parts) + '}'


lines = [
    '-- Generated by tools\\zygor-coa\\talentdata\\build_ztacoa_data.py on %s. Do not edit by hand.' % time.strftime('%Y-%m-%d'),
    '-- Leveling builds: Ascension Sidekick (https://ascensionsidekick.com), the CoA community build site.',
    '-- Node -> spell IDs: the CoA client patch\'s CoATalentNodeData (captured Ascension CoA builder data).',
    '-- Each pick: n = name, node = tree node ID, kind = A (ability) / T (talent), spells = one spell per rank,',
    '-- rank = which rank this pick asks for, lvl = suggested level, rl = auto-granted at level, ae/te = cost.',
    'ZygorTalentAdvisorCOA_Data = {',
    '\tsource = "Ascension Sidekick (ascensionsidekick.com)",',
    '\tgenerated = "%s",' % time.strftime('%Y-%m-%d'),
    '\tclasses = {',
]
picks = 0
for site_name, (token, cfile) in sorted(CLASSES.items(), key=lambda kv: kv[1][0]):
    specs = LB.get(site_name)
    if not specs: continue
    lines.append('\t\t["%s"] = { name = %s, classFile = "%s",' % (token, lua_str(site_name), cfile))
    al = aliases.get(cfile, {})
    lines.append('\t\t\taliases = {%s},' % ', '.join('[%s]=%s' % (lua_str(k), lua_str(v)) for k, v in sorted(al.items())))
    lines.append('\t\t\tspecs = {')
    for spec, b in sorted(specs.items()):
        lines.append('\t\t\t\t[%s] = { role = %s, keystone = %s,' % (lua_str(spec), lua_str(b.get('role')), lua_str((b.get('keystone') or '')[:200])))
        for path in ('classPath', 'specPath'):
            seen = {}
            lines.append('\t\t\t\t\t%s = {' % path)
            for p in b.get(path, []):
                seen[p['id']] = seen.get(p['id'], 0) + 1
                lines.append('\t\t\t\t\t\t%s,' % pick_lua(p, seen[p['id']]))
                picks += 1
            lines.append('\t\t\t\t\t},')
        lines.append('\t\t\t\t},')
    lines.append('\t\t\t},')
    lines.append('\t\t},')
lines += ['\t},', '}']
open(OUT, 'w', encoding='utf-8', newline='\r\n').write('\n'.join(lines) + '\n')
print('wrote', OUT, '| classes', len(CLASSES), '| picks', picks)
