
-- Parent zone of each CoA map that the stock client treats as part of a larger zone.
-- CoA made these top-level areas, so GetRealZoneText() names them instead of the zone
-- the guides use. Values are map file names (lowercased), as in ZygorAstrolabeCoAZoneData.
ZygorCoAZoneParents = {
	[1] = {
		["ammenvalestart"] = "azuremystisle",
		["burningbladecoven"] = "durotar",
		["campnarachestart"] = "mulgore",
		["cavernsoftime"] = "tanaris",
		["dustwindcave"] = "durotar",
		["felrock"] = "teldrassil",
		["lowerbanethilbarrowden"] = "teldrassil",
		["maraudonorange"] = "desolace",
		["palemanerock"] = "mulgore",
		["shadowglenstart"] = "teldrassil",
		["shadowthreadcave"] = "teldrassil",
		["skullrock"] = "durotar",
		["stillpinehold"] = "azuremystisle",
		["thegapingchasm"] = "tanaris",
		["thenoxiouslair"] = "tanaris",
		["theslitheringscar"] = "ungorocrater",
		["theventurecomine"] = "mulgore",
		["tideshollow"] = "azuremystisle",
		["twilightsrun"] = "silithus",
		["valleyoftrialsstart"] = "durotar",
		["wailingcavernsbarrens"] = "barrens",
	},
	[2] = {
		["amanicatacombs"] = "ghostlands",
		["blackrockmountain"] = "burningsteppes",
		["coldridgepass"] = "dunmorogh",
		["coldridgevalley"] = "dunmorogh",
		["deadmineswestfall"] = "westfall",
		["deathknellstart"] = "tirisfal",
		["echoridgemine"] = "elwynn",
		["golbolarquarry"] = "dunmorogh",
		["goldcoastquarry"] = "westfall",
		["jangolodemine"] = "westfall",
		["jasperlodemine"] = "elwynn",
		["nightwebshollow"] = "tirisfal",
		["northshire"] = "elwynn",
		["scarletmonasteryentrance"] = "tirisfal",
		["sunstriderislestart"] = "eversongwoods",
		["thegrizzledden"] = "dunmorogh",
		["uldamanin"] = "badlands",
		["upperfargodeepmine"] = "elwynn",
	},
}
